workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

stages:
  - test
  - sast
  - secret_detection
  - build
  - release

include:
  - local: '.gitlab/build.yml'
  - local: '.gitlab/release.yml'
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml